### ISSUE TITLE
verifyAuthenticationRequest() fails due to dev.uniresolver.io being down

### ISSUE THREAD

**Issue by astanciu** [Sphereon-Opensource/did-auth-siop#12]
About 30-50% of the time calls to `verifyAuthenticationRequest()` fail. Network tab shows that requests are pending/failing for DID resolution against `https://dev.uniresolver.io/1.0/identifiers/did:ethr:.....`.

How can this resolver be replaced with something else?

**Comment by nklomp** [comment]
Hi @astanciu 

The uniresolver is being hosted by DIF I believe and outside of this projects scope. That being sad, there are 2 ways to go about it. https://github.com/Sphereon-Opensource/did-auth-siop/blob/develop/src/main/functions/DIDResolution.ts is responsible for the actual DID resolution in the project

1) You can point to another UniResolver installation. Possibly one you setup yourself. This can be done by providing the URL of the Universal Resolver installation through the `opts.verification.resolveOpts.resolveUrl` option.

2) Change the resolver for your method directly if supported by https://github.com/decentralized-identity/did-resolver by updating the `opts.verification.resolveOpts.resolver` parameter with your resolver.

Given we use our Universal Resolver Client package from https://github.com/Sphereon-Opensource/did-uni-client , you can use all the configuration parameters including environement variables available to create your own resolver for 1 or more DID methods, which you could pass on to the parameter mentiond in 2)

Also see https://github.com/Sphereon-Opensource/did-auth-siop#did-resolution for a bit more information
